DROP TABLE IF EXISTS approvals;
DROP TABLE IF EXISTS tool_executions;
DROP TABLE IF EXISTS workflow_steps;
DROP TABLE IF EXISTS workflows;
DROP TABLE IF EXISTS leads;
DROP TABLE IF EXISTS contacts;
DROP TABLE IF EXISTS companies;
